(()=>{
 let context,bgmGain,seGain,current,scene='menu',revision=0,unlocked=false,paused=false;
 const cache=new Map();let levels={bgm:.45,se:.65,muted:false};
 const get=async name=>{if(!cache.has(name))cache.set(name,fetch((window.CoastAsset||'')+'audio/'+name+'.wav').then(r=>{if(!r.ok)throw Error('Audio '+r.status);return r.arrayBuffer()}).then(b=>context.decodeAudioData(b)));return cache.get(name);};
 const gain=()=>{if(!context)return;bgmGain.gain.cancelScheduledValues(context.currentTime);if(context.currentTime<duckUntil)bgmGain.gain.setTargetAtTime(levels.muted?0:levels.bgm,duckUntil,.15);bgmGain.gain.setTargetAtTime(levels.muted?0:levels.bgm*(context.currentTime<duckUntil?.25:1),context.currentTime,.05);seGain.gain.setTargetAtTime(levels.muted?0:levels.se,context.currentTime,.02);};
 async function play(){if(!unlocked||paused)return;const rev=++revision;const name=scene;try{const buffer=await get(name);if(rev!==revision||paused)return;const source=context.createBufferSource(),fade=context.createGain();source.buffer=buffer;source.loop=true;source.connect(fade);fade.connect(bgmGain);fade.gain.setValueAtTime(0,context.currentTime);fade.gain.linearRampToValueAtTime(1,context.currentTime+.5);source.start();if(current){current.fade.gain.cancelScheduledValues(context.currentTime);current.fade.gain.setTargetAtTime(0,context.currentTime,.15);current.source.stop(context.currentTime+.8);}current={source,fade};}catch(e){console.warn('Audio unavailable',e.message);}}
 async function unlock(){if(!context){context=new (window.AudioContext||window.webkitAudioContext)();bgmGain=context.createGain();seGain=context.createGain();bgmGain.connect(context.destination);seGain.connect(context.destination);gain();}await context.resume();if(!unlocked){unlocked=true;play();}}
 async function effect(name='click'){try{await unlock();const buffer=await get(name);if(paused)return;const s=context.createBufferSource();s.buffer=buffer;s.connect(seGain);s.start();}catch{}}
 document.addEventListener('pointerdown',()=>unlock().catch(()=>{}),{passive:true});
 document.addEventListener('click',e=>{if(e.target.closest('button')&&!e.target.closest('#pedals'))effect();},true);
 document.addEventListener('visibilitychange',()=>{paused=document.hidden;if(!context)return;if(paused)context.suspend();else context.resume().then(()=>{if(!current)play();}).catch(()=>{});});
 let motor,motorGain,motorFilter;
function engine(active,speed,gear,vehicle,throttle=0){if(!context||!unlocked)return;if(!motor){motor=context.createOscillator();motor.type='sawtooth';motorGain=context.createGain();motorGain.gain.value=0;motorFilter=context.createBiquadFilter();motorFilter.type='lowpass';motorFilter.frequency.value=550;motor.connect(motorFilter);motorFilter.connect(motorGain);motorGain.connect(seGain);motor.start();}const cycle=vehicle==='bicycle',rpm=55+(speed%11)*10+Math.min(speed,60)+throttle*18;motor.frequency.setTargetAtTime(cycle?18+speed*1.5:rpm,context.currentTime,.12);motorFilter.frequency.setTargetAtTime(cycle?180:500+speed*15,context.currentTime,.1);motorGain.gain.setTargetAtTime(active&&!paused?(cycle?(speed>1?.012:0):.025+throttle*.015+Math.min(speed/60,1)*.025):0,context.currentTime,.08);}
function startTone(go){if(!context||!unlocked||paused)return;const o=context.createOscillator(),g=context.createGain();o.type='square';o.frequency.value=go?880:330;o.connect(g);g.connect(seGain);g.gain.setValueAtTime(.045,context.currentTime);g.gain.exponentialRampToValueAtTime(.001,context.currentTime+(go?.55:.18));o.start();o.stop(context.currentTime+(go?.6:.2));}
const fanfareKeys=new Set();let duckUntil=0;
function fanfare(rank,count,key){
 if(fanfareKeys.has(key)||!context||!unlocked||paused)return;fanfareKeys.add(key);
 const group=rank===1?'winner':rank===count?'last':rank<=3?'podium':'middle';
 const notes={winner:[60,64,67,72,67,72,76,79],podium:[60,64,67,69,67,72],middle:[60,62,64,67,64],last:[55,60,62,64,60]}[group];
 const now=context.currentTime;duckUntil=now+3;bgmGain.gain.setTargetAtTime(levels.muted?0:levels.bgm*.25,now,.06);
 notes.forEach((note,i)=>{for(const interval of [0,7]){const o=context.createOscillator(),g=context.createGain(),start=now+i*.21; o.type=group==='winner'?'triangle':'sine';o.frequency.value=440*Math.pow(2,(note+interval-69)/12);o.connect(g);g.connect(seGain);g.gain.setValueAtTime(0,start);g.gain.linearRampToValueAtTime(interval?.035:.09,start+.015);g.gain.exponentialRampToValueAtTime(.001,start+(i===notes.length-1?1:.32));o.start(start);o.stop(start+1.1);}});
 bgmGain.gain.setTargetAtTime(levels.muted?0:levels.bgm,duckUntil,.15);
}
window.ClubAudio={effect,engine,startTone,fanfare,setScene(value){if(value===scene)return;scene=value;play();},settings(value){levels=value;gain();},get status(){return{unlocked,scene,state:context?.state,levels:{...levels},decoded:cache.size};}};
})();