// Original procedural compositions. No third-party recordings or melodies.
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve('Assets/WebGLTemplates/CoastRacer/audio');fs.mkdirSync(root,{recursive:true});
const sr=22050;let seed=173;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296*2-1;};
const note=n=>440*Math.pow(2,(n-69)/12);
function wav(name,buffer){let peak=0,sum=0;for(const v of buffer)peak=Math.max(peak,Math.abs(v));const scale=.76/Math.max(.76,peak);const out=Buffer.alloc(44+buffer.length*2);out.write('RIFF');out.writeUInt32LE(out.length-8,4);out.write('WAVEfmt ',8);out.writeUInt32LE(16,16);out.writeUInt16LE(1,20);out.writeUInt16LE(1,22);out.writeUInt32LE(sr,24);out.writeUInt32LE(sr*2,28);out.writeUInt16LE(2,32);out.writeUInt16LE(16,34);out.write('data',36);out.writeUInt32LE(buffer.length*2,40);for(let i=0;i<buffer.length;i++){const fade=Math.min(1,i/90,(buffer.length-1-i)/90);const v=buffer[i]*scale*fade;sum+=v*v;out.writeInt16LE(Math.round(Math.max(-1,Math.min(1,v))*32767),44+i*2);}fs.writeFileSync(path.join(root,name+'.wav'),out);return{name,duration:buffer.length/sr,peak:peak*scale,rms:Math.sqrt(sum/buffer.length),bytes:out.length};}
function compose(name,bpm,bars,kind){const beat=60/bpm,length=Math.round(bars*4*beat*sr),a=new Float32Array(length);
 function tone(t,d,midi,vol,voice=0){const start=Math.round(t*sr),samples=Math.round(d*sr),freq=note(midi);for(let i=0;i<samples;i++){const sec=i/sr,p=i/samples,env=Math.min(1,sec/(voice===0?.08:.008))*Math.pow(1-p,voice===0?1:2);const wave=Math.sin(2*Math.PI*freq*sec)+.24*Math.sin(4*Math.PI*freq*sec)+.08*Math.sin(6*Math.PI*freq*sec);a[(start+i)%length]+=wave*env*vol;}}
 function drum(t,type,vol){const start=Math.round(t*sr),samples=Math.round((type===0?.28:type===1?.16:.06)*sr);for(let i=0;i<samples;i++){let sec=i/sr,v=type===0?Math.sin(2*Math.PI*(45*sec+12*(1-Math.exp(-sec*22))))*Math.exp(-sec*20):rnd()*Math.exp(-sec*(type===1?35:85));a[(start+i)%length]+=v*vol;}}
 const roots=kind===2?[50,53,58,57]:[50,46,53,48];const melody=kind===2?[12,16,19,24,19,16,14,12]:[12,19,22,19,15,14,10,7];
 for(let bar=0;bar<bars;bar++){const rootNote=roots[Math.floor(bar/2)%4],base=bar*4*beat;for(const interval of [0,7,10,14])tone(base,beat*3.9,rootNote+interval,.045,0);
  for(let b=0;b<4;b++){tone(base+b*beat,beat*.8,rootNote-12,.14,1);drum(base+b*beat,0,kind===1?.32:.20);if(b%2)drum(base+b*beat,1,.095);for(let half=0;half<2;half++){drum(base+(b+half*.5)*beat,2,.035);const m=melody[(bar*2+b*2+half)%melody.length];tone(base+(b+half*.5)*beat,beat*.4,rootNote+m,(kind===0?.04:.065)*(bar%4===3?.6:1),1);}}
  if(kind===2)tone(base,beat*2,rootNote+24,.07,0);
 }
 // Short musical delay, wrapped so the loop remains cyclic.
 const dry=a.slice(),offset=Math.round(beat*.75*sr);for(let i=0;i<length;i++)a[(i+offset)%length]+=dry[i]*.16;
 return wav(name,a);
}
const report=[compose('menu',96,16,0),compose('race',128,16,1),compose('result',104,8,2)];
for(const name of ['click','coin','special']){const duration=name==='click'?.18:.35,a=new Float32Array(Math.round(sr*duration));for(let i=0;i<a.length;i++){const t=i/sr,env=Math.min(1,t/.004)*Math.exp(-t*(name==='click'?28:13));const f=name==='click'?74+80*Math.exp(-t*35):name==='coin'?880+700*t:140+900*t;a[i]=(Math.sin(2*Math.PI*f*t)*.45+rnd()*(name==='click'?.12:.015))*env;}report.push(wav(name,a));}
fs.writeFileSync(path.join(root,'manifest.json'),JSON.stringify({author:'Coast Racer project',method:'Original additive synthesis, original D-minor chord sequences and percussion; generated by Deployment/Generate-Audio.mjs',sampleRate:sr,files:report},null,2));console.log(JSON.stringify(report));