import fs from 'node:fs';
import path from 'node:path';
import {spawn} from 'node:child_process';
const base=process.argv[2]||'http://127.0.0.1:5080';
const logs=path.resolve('Logs');fs.mkdirSync(logs,{recursive:true});
const edge=spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',['--headless=new','--no-first-run','--no-default-browser-check','--remote-debugging-port=9228','--enable-unsafe-swiftshader','--use-angle=swiftshader','--window-size=1100,650','--user-data-dir='+path.resolve('Temp/ProRacerBrowserCheck'),'about:blank'],{windowsHide:true,stdio:'ignore'});
const delay=ms=>new Promise(r=>setTimeout(r,ms));const errors=[];const checks=[];
function assert(value,label){if(!value)throw Error(label);checks.push(label);console.log('PASS '+label);}
async function session(url){
 const ws=new WebSocket(url);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});
 let id=0;const pending=new Map();
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);else if(m.method==='Runtime.consoleAPICalled'&&m.params.type==='error')errors.push(m.params.args.map(a=>a.value||a.description).join(' '));};
 const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;const timer=setTimeout(()=>{pending.delete(n);reject(Error('CDP timeout '+method));},25000);pending.set(n,{resolve,reject,timer});ws.send(JSON.stringify({id:n,method,params}));});
 const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.text);return r.result.value;};
 await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1100,height:650,deviceScaleFactor:1,mobile:true});await call('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});
 return{ws,call,evaluate};
}
async function waitFor(tab,expression,seconds=70){for(let i=0;i<seconds*2;i++){if(await tab.evaluate(expression))return true;await delay(500);}return false;}
async function screenshot(tab,file){const data=await tab.call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(logs,file),Buffer.from(data.data,'base64'));}
let first,second;
try{
 let tabs;
 for(let i=0;i<40;i++){try{tabs=await(await fetch('http://127.0.0.1:9228/json/list')).json();if(tabs.length)break;}catch{}await delay(500);}
 first=await session(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);
 await first.call('Page.navigate',{url:base+'/play/'});
 assert(await waitFor(first,'window.Racer && document.querySelector("#loading").hidden'),'Web game loads');
 await first.evaluate('localStorage.removeItem("cr.lang")');await first.call('Page.reload');
 assert(await waitFor(first,'window.Racer && document.querySelector("#loading").hidden'),'Fresh Japanese session loads');
 assert(await first.evaluate('document.documentElement.lang==="ja" && document.querySelector("#singleMode").textContent==="シングルプレイ"'),'Japanese is default');
 await screenshot(first,'pro-menu.png');
 assert(await first.evaluate('getComputedStyle(document.querySelector("#game")).visibility==="hidden"'),'Menu hides 3D world');
 await first.evaluate('document.querySelector("#menuSettings").click()');
 assert(await first.evaluate('!document.querySelector("#settingsOverlay").hidden && document.querySelector("header #language")===null'),'Settings contains language and dark modal');
 await screenshot(first,'pro-settings.png');
 await first.evaluate('document.querySelector("#settingsTitle").click()');
 assert(await first.evaluate('!document.querySelector("#settingsOverlay").hidden'),'Inside dialog does not dismiss');
 await first.evaluate('document.querySelector("#closeSettings").click()');
 assert(await first.evaluate('document.querySelector("#settingsOverlay").hidden'),'Close button dismisses dialog');
 await first.evaluate('document.querySelector("#menuSettings").click()');
 await first.call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:9,x:20,y:120}]});
 await first.call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await delay(250);
 assert(await first.evaluate('document.querySelector("#settingsOverlay").hidden && Racer.screen==="menu"'),'Backdrop dismisses without navigation');
 await first.evaluate('document.querySelector("#menuSettings").click()');
 await first.call('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
 assert(await first.evaluate('document.querySelector("#settingsOverlay").hidden'),'Escape dismisses dialog');
 await first.evaluate('document.querySelector("#menuSettings").click()');
 await first.evaluate('document.querySelector("#language").value="en";document.querySelector("#language").dispatchEvent(new Event("change"))');
 await first.call('Page.reload');assert(await waitFor(first,'window.Racer && document.querySelector("#loading").hidden'),'Language reload');
 assert(await first.evaluate('document.documentElement.lang==="en"'),'English persists');
 await first.evaluate('document.querySelector("#language").value="ja";document.querySelector("#language").dispatchEvent(new Event("change"));document.querySelector("#closeSettings").click();document.querySelector("#singleMode").click();document.querySelector("[data-track=suzuka]").click()');
 assert(await waitFor(first,'Racer.telemetry?.track==="suzuka"'),'Suzuka-inspired track switches');
 assert(await first.evaluate('getComputedStyle(document.querySelector("#game")).visibility==="hidden" && Racer.screen==="courses"'),'Selected course remains hidden');
 await screenshot(first,'pro-suzuka-menu.png');
 await first.evaluate('document.querySelector("#solo").click()');
 assert(await waitFor(first,'Racer.telemetry?.phase==="race"'),'Countdown starts solo race');
 assert(await first.evaluate('getComputedStyle(document.querySelector("#game")).visibility==="visible"'),'Race reveals world');
 const startYaw=await first.evaluate('Racer.telemetry.cars[0].yaw');
 const rects=await first.evaluate('["wheel","throttle","brake"].map(id=>{let r=document.getElementById(id).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,h:r.height}})');
 await first.call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:rects[0].x-35,y:rects[0].y},{id:2,x:rects[1].x,y:rects[1].y}]});
 await delay(1000);
 assert(await first.evaluate('Number(document.querySelector("#wheel").getAttribute("aria-valuenow")) < -80'),'Hold left steers left without dragging');
 await first.call('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:rects[0].x+35,y:rects[0].y-25},{id:2,x:rects[1].x,y:rects[1].y}]});
 await delay(1000);
 assert(await first.evaluate('Number(document.querySelector("#wheel").getAttribute("aria-valuenow")) > 80'),'Move held finger right reverses steering');
 await first.call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 const drive=await first.evaluate('Racer.telemetry.cars[0]');
 assert(drive.speed>2,'Touch accelerator moves car');
 assert(Math.abs(drive.yaw-startYaw)>.03,'Virtual wheel changes heading');
 await screenshot(first,'pro-driving.png');
 await delay(600);
 assert(await first.evaluate('Math.abs(Number(document.querySelector("#wheel").getAttribute("aria-valuenow"))) < 3'),'Release recenters wheel');
 await first.call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:3,x:rects[2].x,y:rects[2].y}]});await delay(1200);await first.call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 assert(await first.evaluate('Racer.telemetry.cars[0].speed')<drive.speed,'Touch brake slows car');
 await first.evaluate('document.querySelector("#raceSettings").click()');await delay(400);
 const settingsTime=await first.evaluate('Racer.telemetry.cars[0].elapsed');await delay(500);
 assert(await first.evaluate('Racer.telemetry.cars[0].elapsed')===settingsTime,'Solo settings pauses race');
 await first.evaluate('document.querySelector("#closeSettings").click()');
 assert(await waitFor(first,'Racer.telemetry?.phase==="race"',5),'Closing solo settings resumes race');
 await first.call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:8,x:rects[0].x-35,y:rects[0].y}]});await delay(400);
 await first.call('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await delay(600);
 assert(await first.evaluate('Math.abs(Number(document.querySelector("#wheel").getAttribute("aria-valuenow"))) < 3'),'Touch cancellation releases steering');
 await first.evaluate('document.querySelector("#pauseButton").click()');await delay(400);
 const elapsed=await first.evaluate('Racer.telemetry.cars[0].elapsed');await delay(600);
 assert(await first.evaluate('Racer.telemetry.cars[0].elapsed')===elapsed,'Pause freezes race time');
 await first.evaluate('document.querySelector("#pauseMenu").click();document.querySelector("#onlineMode").click();document.querySelector("[data-track=ridge]").click();document.querySelector("#solo").click();document.querySelector("#name").value="ブラウザ甲";document.querySelector("#createRoom").click()');
 assert(await waitFor(first,'Racer.online && Racer.screen==="lobby"',15),'Browser creates room');
 assert(await first.evaluate('getComputedStyle(document.querySelector("#game")).visibility==="hidden"'),'Online lobby hides world');
 const code=await first.evaluate('document.querySelector("#codeDisplay").textContent');
 const target=await first.call('Target.createTarget',{url:base+'/play/'});
 tabs=await(await fetch('http://127.0.0.1:9228/json/list')).json();second=await session(tabs.find(t=>t.id===target.targetId).webSocketDebuggerUrl);
 assert(await waitFor(second,'window.Racer && document.querySelector("#loading").hidden'),'Second game client loads');
 await second.evaluate('document.querySelector("#onlineMode").click();document.querySelector("#solo").click();document.querySelector("#name").value="ブラウザ乙";document.querySelector("#roomCode").value='+JSON.stringify(code)+';document.querySelector("#joinRoom").click()');
 assert(await waitFor(second,'Racer.online && Racer.screen==="lobby"',15),'Second browser joins same room');
 await first.evaluate('document.querySelector("#ready").click()');await second.evaluate('document.querySelector("#ready").click()');
 assert(await waitFor(first,'!document.querySelector("#startOnline").disabled',10),'Both clients ready');
 await first.evaluate('document.querySelector("#startOnline").click()');
 await first.call('Page.bringToFront');
 assert(await waitFor(first,'Racer.telemetry?.phase==="race"',15),'Owner enters online race');
 await second.call('Page.bringToFront');
 assert(await waitFor(second,'Racer.telemetry?.phase==="race"',15),'Guest enters same online race');
 await first.call('Page.bringToFront');
 await first.evaluate('document.querySelector("#raceSettings").click()');
 const before=await first.evaluate('Racer.telemetry.cars[0].elapsed');await delay(1200);
 assert(await first.evaluate('!document.querySelector("#settingsOverlay").hidden && Racer.telemetry.cars[0].elapsed')>before,'Online race continues behind settings');
 await first.evaluate('document.querySelector("#closeSettings").click()');
 await screenshot(first,'pro-online.png');await screenshot(second,'pro-online-guest.png');
 await first.evaluate('document.querySelector("#resultMenu").click()');await second.evaluate('document.querySelector("#resultMenu").click()');
 assert(errors.length===0,'No browser runtime errors');
 fs.writeFileSync(path.join(logs,'pro-browser-checks.json'),JSON.stringify({checks,errors,note:'Desktop Edge with mobile emulation; not physical iPhone/Android testing.'},null,2));
}catch(e){console.error(e);fs.writeFileSync(path.join(logs,'pro-browser-failure.json'),JSON.stringify({error:String(e),checks,errors},null,2));if(first)try{await screenshot(first,'pro-browser-failure.png')}catch{}process.exitCode=1;}
finally{if(first)try{await first.call('Browser.close')}catch{}first?.ws.close();second?.ws.close();edge.kill();}
